import jsPDF from 'jspdf';
import 'jspdf-autotable';

/* ───── CSV EXPORT ───── */

export function exportCSV(data, filename = 'export.csv') {
  if (!data || data.length === 0) return;
  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(','),
    ...data.map(row =>
      headers.map(h => {
        const val = row[h] ?? '';
        const str = String(val).replace(/"/g, '""');
        return `"${str}"`;
      }).join(',')
    ),
  ];
  downloadBlob(csvRows.join('\n'), filename, 'text/csv');
}

/* ───── PDF EXPORT ───── */

export function exportPDF(data, title = 'Report', filename = 'export.pdf', projectInfo = {}) {
  if (!data || data.length === 0) return;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  // Header
  doc.setFontSize(18);
  doc.setTextColor(10, 34, 64);
  doc.text('Modular Planner Pro', 14, 15);

  doc.setFontSize(13);
  doc.setTextColor(50, 50, 50);
  doc.text(title, 14, 23);

  // Project info
  let y = 30;
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  if (projectInfo.name) { doc.text(`Project: ${projectInfo.name}`, 14, y); y += 5; }
  if (projectInfo.client_name) { doc.text(`Client: ${projectInfo.client_name}`, 14, y); y += 5; }
  if (projectInfo.date) { doc.text(`Date: ${projectInfo.date}`, 14, y); y += 5; }
  y += 2;

  // Table
  const headers = Object.keys(data[0]);
  const displayHeaders = headers.map(h => h.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()));

  doc.autoTable({
    startY: y,
    head: [displayHeaders],
    body: data.map(row => headers.map(h => row[h] ?? '')),
    styles: {
      fontSize: 7,
      cellPadding: 2,
      textColor: [30, 30, 30],
    },
    headStyles: {
      fillColor: [10, 34, 64],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7,
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount}  •  Generated by Modular Planner Pro`,
      14,
      doc.internal.pageSize.height - 8
    );
  }

  doc.save(filename);
}

/* ───── Helpers ───── */

function downloadBlob(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
